### ISSUE TITLE
Outdated libsass bindings.

### ISSUE THREAD

**Issue by turboMaCk** [jakubfijalkowski/hlibsass#15]
It seems this library defines bindings to `sass_option_get_plugin_path` and `sass_option_get_include_path` in https://github.com/jakubfijalkowski/hlibsass/blob/9b60d51b2195b6930df7b98b7243c18f79a11a05/Bindings/Libsass/Context.hs which were removed from from libsass headers  int commit https://github.com/sass/libsass/commit/375394819b001389c7f61d3de042b55d3f460bde.

This causes compilation failure

```
error: undefined reference to 'sass_option_get_plugin_path_size'
```

**Comment by jakubfijalkowski** [comment]
Hello!

Thanks for the report!

It seems that you're using mismatched `libsass` and `hLibsass` version. You need to use exact combination of `hLibsass` and `libsass` for it to compile (one can use some weak binding to match more versions, but I'm not that fluent in linking options - that's why hLibsass is compiled statically with libsass).

I mistakenly stated that v0.1.10.x works with libsass 3.6.3 but that is not true. I've fixed the README now - you need to use 3.6.4 with v0.1.10.1.

These methods have been re-introduced in [this commit](https://github.com/sass/libsass/commit/7c8a545f47e335d790e62d2a457ed23cb86b3105), that's why they are in v0.1.10.1 but not in v0.1.9.0.

**Comment by turboMaCk** [comment]
I've tried again using `libsass-3.6.4` and `hlibsass-0.1.10.1` and it works. Thanks.
